[tools]
"aqua:JanDeDobbeleer/oh-my-posh" = "latest"
atuin = "latest"
carapace = "latest"
chezmoi = "latest"
fd = "latest"
neovim = "latest"
ripgrep = "latest"
zoxide = "latest"

go = "latest"
helm = "latest"
kubectl = "latest"
node = "latest"
rust = "latest"
glab = "latest"
gh = "latest"
podman = "latest"

[settings]
idiomatic_version_file_enable_tools = ["java"]
